{
    "CreationTimeUnixTimeInMs": 1518545061791,
    "Creator": "admin",
    "Description": "Test Connectivity",
    "Id": -1,
    "IntegrationIdentifier": "RSANetWitnessPlatform",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1518545061791,
    "Name": "Ping",
    "Parameters": [],
    "ScriptResultName": "is_success",
    "Type": 0,
    "Version": 1.0,
    "SimulationDataJson": "{\"Entities\":[]}"
}