### Json Structure Params ###
json_result_has_entities: no
entity_result_list_path: '[{stepInstanceName}.JsonResult]'
json_result_list: '[{stepInstanceName}.JsonResult]'

### HTML Structure Params ###
main_text_singular: USER FOUND
main_text_plural: USERS FOUND

import_svg_from_integration: yes

### Table Structure Params ###
table_data:
  - header: Name
    value:
      keys_to_display:
        - name.fullName

  - header: Primary Email
    value:
      keys_to_display:
        - primaryEmail

  - header: Admin
    value:
      keys_to_display:
        - isAdmin

  - header: Suspended
    value:
      keys_to_display:
        - suspended

  - header: Last Login Time
    value:
      keys_to_display:
        - lastLoginTime

  - header: Archived
    value:
      keys_to_display:
        - archived

  - header: Organization
    value:
      pass_to_function: get_organizations_departments
      keys_to_display:
        - organizations


