{
    "CreationTimeUnixTimeInMs": 1516023545506,
    "Creator": "admin",
    "Description": "Remove URL from the Checkpoint FireWall Group",
    "Id": -1,
    "IntegrationIdentifier": "CheckPointFirewall",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1516023545506,
    "Name": "Remove Url From Group",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1516022322464,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify the name of the group from which you want to remove URL.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1516022322464,
            "Name": "URLs Group Name",
            "Type": 0,
            "Value": ""
        }
    ], 
    "ScriptResultName": "is_unblocked", 
    "SimulationDataJson": "{\"Entities\": [\"DestinationURL\"]}", 
    "Type": 0, 
    "Version": 0.0
}