INTEGRATION_NAME = 'MicrosoftAzureSentinel'
PRODUCT_NAME = 'Microsoft Azure Sentinel'


# ACTIONS NAMES
PING_SCRIPT_NAME = f'{INTEGRATION_NAME} - Ping'
LIST_INCIDENTS_SCRIPT_NAME = f'{INTEGRATION_NAME} - List Incidents'
UPDATE_INCIDENT_DETAILS_SCRIPT_NAME = f'{INTEGRATION_NAME} - Update Incident Details'
GET_ALERT_RULE_DETAILS_SCRIPT_NAME = f'{INTEGRATION_NAME} - Get Alert Rule Details'
UPDATE_INCIDENT_LABELS_SCRIPT_NAME = f'{INTEGRATION_NAME} - Update Incident Labels'
GET_INCIDENT_STATISTICS_SCRIPT_NAME = f'{INTEGRATION_NAME} - Get Incident Statistics'
LIST_CUSTOM_HUNTING_RULES_SCRIPT_NAME = f'{INTEGRATION_NAME} - List Custom Hunting Rules'
GET_CUSTOM_HUNTING_RULE_DETAILS_SCRIPT_NAME = f'{INTEGRATION_NAME} - Get Custom Hunting Rule'
CREATE_CUSTOM_HUNTING_RULES_SCRIPT_NAME = f'{INTEGRATION_NAME} - Create Custom Hunting Rule'
DELETE_CUSTOM_HUNTING_RULES_SCRIPT_NAME = f'{INTEGRATION_NAME} - Delete Custom Hunting Rule'
UPDATE_CUSTOM_HUNTING_RULES_SCRIPT_NAME = f'{INTEGRATION_NAME} - Update Custom Hunting Rule'
LIST_ALERT_RULES_SCRIPT_NAME = f'{INTEGRATION_NAME} - List Alert Rules'
CREATE_ALERT_RULE_SCRIPT_NAME = f'{INTEGRATION_NAME} - Create Alert Rule'
DELETE_ALERT_RULE_SCRIPT_NAME = f'{INTEGRATION_NAME} - Delete Alert Rule'
UPDATE_ALERT_RULE_SCRIPT_NAME = f'{INTEGRATION_NAME} - Update Alert Rule'
RUN_KQL_QUERY_SCRIPT_NAME = f'{INTEGRATION_NAME} - Run KQL Query'
RUN_CUSTOM_HUNTING_RULE_SCRIPT_NAME = f'{INTEGRATION_NAME} - Run Custom Hunting Rule'
ADD_COMMENT_TO_INCIDENT_SCRIPT_NAME = f'{INTEGRATION_NAME} - Add Comment to Incident'

# TABLES NAMES
INCIDENTS_TABLE_NAME = 'Incidents'
ALERT_RULE_DETAILS_TABLE = 'Microsoft Azure Sentinel Alert Rule Details'
ALERT_RULES_TABLE_NAME = 'Microsoft Azure Sentinel Alert Rules found'
INCIDENT_STATISTICS_BY_SEVERITY_TABLE_NAME = f'{PRODUCT_NAME} Incident statistics by Severity'
INCIDENT_STATISTICS_BY_STATUS_TABLE_NAME = f'{PRODUCT_NAME} Incident statistics by Status'
HUNTING_RULES_TABLE_NAME = f'{PRODUCT_NAME} hunting rules found'
CUSTOM_HUNTING_RULE_DETAILS_TABLE_NAME = f'{PRODUCT_NAME} Hunting Rule Details'
KQL_QUERY_RESULTS = 'KQL Query results'
HUNTING_RULE_RESULTS_TABLE_NAME = f'{PRODUCT_NAME} hunting rule results'


SPECIAL_CHARACTERS_MAPPING = {
    "\r": "",
    "\n": "",
    "\u200b": ""
}
SCHEDULED_ALERT_TYPE_STRING = 'Scheduled Alerts'
SCHEDULED_ALERT_EVENT_KIND = 'ScheduledAlert'
NRT_ALERT_TYPE_STRING = 'NRT Alerts'
NRT_ALERT_EVENT_KIND = 'NRT'
ALERT_TYPES_WITH_EVENTS = [SCHEDULED_ALERT_TYPE_STRING, NRT_ALERT_TYPE_STRING]
PLACEHOLDER_START = "["
PLACEHOLDER_END = "]"
CHARACTERS_LIMIT = 256
