{
    "CreationTimeUnixTimeInMs": 1520430101199, 
    "Creator": "admin", 
    "Description": "Retrieve information about assets from AlienVault USM Appliance", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"EntityResult\": {\"model\": null, \"descr\": \"\", \"hostname\": \"Lanthanum\", \"asset_type\": \"Internal\", \"fqdn\": \"\", \"devices\": [], \"asset_value\": \"2\", \"ips\": {\"3.3.3.3\": {\"ip\": \"1.1.1.1\", \"mac\": \"11:DE:B0:DD:54:54\"}}, \"id\": \"123D37D595B800734550B9D9D6A958C6\", \"sensors\": {\"C221234962EA11E697DE0AF71A09DF3B\": {\"ip\": \"1.1.1.1\", \"ctxs\": {\"C228355962EA11E697DE0AF71A09DF3B\": \"AlienVault\"}, \"name\": \"DA\"}}, \"os\": \"Linux\", \"networks\": {\"7E4B12EEFD06A21F898345C2AB46EB10\": {\"ips\": \"1.1.1.1/16\", \"ctx\": \"C228355962EA11E697DE0AF71A09DF3B\", \"name\": \"Pvt_000\"}}, \"icon\": \"\"}, \"Entity\": \"domain.com\"}]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "AlienVaultAppliance", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1520430101199, 
    "Name": "Enrich Assets", 
    "Parameters": [], 
    "ScriptResultName": "success", 
    "SimulationDataJson": "{\"Entities\": [\"HOSTNAME\", \"ADDRESS\"]}", 
    "Type": 0, 
    "Version": 0.0
}