{
    "CreationTimeUnixTimeInMs": 1520430282269, 
    "Creator": "admin", 
    "Description": "Retrieve information about vulnerabilities from AlienVault USM Appliance", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"EntityResult\": [{\"Severity\": \"High\", \"Service\": \"general (0/tcp))\", \"Vulnerability\": \"TCP Sequence Number Approximation Reset Denial of Service Vulnerability\", \"Scan Time\": \"2014-02-26 02:08:59\", \"Asset\": \"Lanthanum (1.1.1.1)\", \"Id\": \"123456\"}, {\"Severity\": \"High\", \"Service\": \"https (443/tcp)\", \"Vulnerability\": \"robot(s).txt exists on the Web Server\", \"Scan Time\": \"2014-02-26 02:08:59\", \"Asset\": \"Lanthanum (1.1.1.1)\", \"Id\": \"123457\"}, {\"Severity\": \"Medium\", \"Service\": \"general (0/tcp))\", \"Vulnerability\": \"TCP timestamps\", \"Scan Time\": \"2014-02-26 02:08:59\", \"Asset\": \"Lanthanum (1.1.1.1)\", \"Id\": \"123458\"}], \"Entity\": \"test\"}]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "AlienVaultAppliance", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1520430282269, 
    "Name": "Enrich Vulnerabilities", 
    "Parameters": [], 
    "ScriptResultName": "success", 
    "SimulationDataJson": "{\"Entities\": [\"HOSTNAME\", \"ADDRESS\"]}", 
    "Type": 0, 
    "Version": 0.0
}