{
    "CreationTimeUnixTimeInMs": 1520430067614,
    "Creator": "admin",
    "Description": "Test Connectivity",
    "Id": -1,
    "IntegrationIdentifier": "AlienVaultAppliance",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1520430067614,
    "Name": "Ping",
    "Parameters": [],
    "ScriptResultName": "success",
    "Type": 0,
    "Version": 0.0,
    "SimulationDataJson": "{\"Entities\": []}"
}