INTEGRATION_IDENTIFIER = "FreshworksFreshservice"
INTEGRATION_DISPLAY_NAME = "Freshservice"

# Actions script name
PING_SCRIPT_NAME = "Ping"
CREATE_TICKET_SCRIPT_NAME = "Create Ticket"
UPDATE_TICKET_SCRIPT_NAME = "Update Ticket"
LIST_TICKETS_SCRIPT_NAME = "List Tickets"
LIST_TICKET_CONVERSATIONS_SCRIPT_NAME = "List Ticket Conversations"
CREATE_AGENT_SCRIPT_NAME = "Create Agent"
UPDATE_AGENT_SCRIPT_NAME = "Update Agent"
DEACTIVATE_AGENT_SCRIPT_NAME = "Deactivate Agent"
LIST_AGENTS_SCRIPT_NAME = "List Agents"
CREATE_REQUESTER_SCRIPT_NAME = "Create Requester"
UPDATE_REQUESTER_SCRIPT_NAME = "Update Requester"
DEACTIVATE_REQUESTER_SCRIPT_NAME = "Deactivate Requester"
LIST_REQUESTERS_SCRIPT_NAME = "List Requesters"
ADD_TICKET_REPLY_SCRIPT_NAME = "Add a Ticket Reply"
ADD_TICKET_NOTE_SCRIPT_NAME = "Add a Ticket Note"
LIST_TICKET_TIME_ENTRIES_SCRIPT_NAME = "List Ticket Time Entries"
ADD_TICKET_TIME_ENTRY_SCRIPT_NAME = "Add Ticket Time Entry"
UPDATE_TICKET_TIME_ENTRY_SCRIPT_NAME = "Update Ticket Time Entry"
DELETE_TICKET_TIME_ENTRY_SCRIPT_NAME = "Delete Ticket Time Entry"

API_LIMIT_ERROR = 429
NOT_FOUND_ERROR = 404
METHOD_NOT_ALLOWED_ERROR = 405
FORBIDDEN_CLIENT_ERROR = 403

ROWS_PER_PAGE_DEFAULT_VALUE = 30
MAX_ROWS_TO_RETURN_DEFAULT_VALUE = 30
START_AT_PAGE_DEFAULT_VALUE = 1

FILE_SIZE_LIMIT = 15728640.0
SEPERATOR = "\n"
LOW_PRIORITY = "Low"
MEDIUM_PRIORITY = "Medium"
HIGH_PRIORITY = "High"
URGENT_PRIORITY = "Urgent"
TICKET_PRIORITIES = [LOW_PRIORITY, MEDIUM_PRIORITY, HIGH_PRIORITY, URGENT_PRIORITY]

OPEN_TICKET = "Open"
PENDING_TICKET = "Pending"
RESOLVED_TICKET = "Resolved"
CLOSED_TICKET = "Closed"
TICKET_STATUSES = [OPEN_TICKET, PENDING_TICKET, RESOLVED_TICKET, CLOSED_TICKET]

INCIDENT_TICKET = "Incident"
SERVICE_REQUEST_TICKET = "Service Request"
ALERT_TICKET = "Alert"
TICKET_TYPES = [INCIDENT_TICKET, SERVICE_REQUEST_TICKET, ALERT_TICKET]

LOW_URGENCY = "Low"
MEDIUM_URGENCY = "Medium"
HIGH_URGENCY = "High"
TICKET_URGENCIES = [LOW_URGENCY, MEDIUM_URGENCY, HIGH_URGENCY]

LOW_IMPACT = "Low"
MEDIUM_IMPACT = "Medium"
HIGH_IMPACT = "High"
TICKET_IMPACTS = [LOW_IMPACT, MEDIUM_IMPACT, HIGH_IMPACT]

AGENT_STATE_ALL = "all"
AGENT_STATE_FULLTIME = "Fulltime"
AGENT_STATE_OCCASIONAL = "Occasional"

EMAIL = "Email"
PORTAL = "Portal"
PHONE = "Phone"
CHAT = "Chat"
FEEDBACK_WIDGET = "Feedback widget"
YAMMER = "Yammer"
AWS_CLOUDWATCH = "AWS Cloudwatch"
PAGERDUTY = "Pagerduty"
WALKUP = "Walkup"
SLACK = "Slack"
TICKET_SOURCE_TYPES = [EMAIL, PORTAL, PHONE, CHAT, FEEDBACK_WIDGET, YAMMER, AWS_CLOUDWATCH, WALKUP, SLACK]

MAPPED_TICKET_PRIORITIES = {
    1: LOW_PRIORITY,
    2: MEDIUM_PRIORITY,
    3: HIGH_PRIORITY,
    4: URGENT_PRIORITY
}
MAPPED_TICKET_STATUSES = {
    2: OPEN_TICKET,
    3: PENDING_TICKET,
    4: RESOLVED_TICKET,
    5: CLOSED_TICKET
}
MAPPED_TICKET_SOURCES = {
    1: EMAIL,
    2: PORTAL,
    3: PHONE,
    4: CHAT,
    5: FEEDBACK_WIDGET,
    6: YAMMER,
    7: AWS_CLOUDWATCH,
    8: PAGERDUTY,
    9: WALKUP,
    10: SLACK
}
CONVERSATION_SOURCE_EMAIL = "Email"
FORM = "Form"
NOTE = "Note"
STATUS = "Status"
META = "Meta"
FEEDBACK = "Feedback"
FORWARD_EMAIL = "Forward Email"
MAPPED_CONVERSATION_SOURCE_TYPES = {
    0: CONVERSATION_SOURCE_EMAIL,
    1: FORM,
    2: NOTE,
    3: STATUS,
    4: META,
    5: FEEDBACK,
    6: FORWARD_EMAIL
}
MAPPED_NUMERIC_TICKET_PRIORITIES = {
    LOW_PRIORITY: 1,
    MEDIUM_PRIORITY: 2,
    HIGH_PRIORITY: 3,
    URGENT_PRIORITY: 4
}
MAPPED_NUMERIC_TICKET_STATUSES = {
    OPEN_TICKET: 2,
    PENDING_TICKET: 3,
    RESOLVED_TICKET: 4,
    CLOSED_TICKET: 5
}
MAPPED_NUMERIC_TICKET_URGENCIES = {
    LOW_URGENCY: 1,
    MEDIUM_URGENCY: 2,
    HIGH_URGENCY: 3
}
MAPPED_NUMERIC_TICKET_IMPACTS = {
    LOW_IMPACT: 1,
    MEDIUM_IMPACT: 2,
    HIGH_IMPACT: 3
}

# Tickets Connector
TICKETS_CONNECTOR_NAME = "Freshservice Tickets Connector"

DEFAULT_TIME_FRAME = 24
MAX_TICKETS_PER_CYCLE_DEFAULT_VALUE = 30

WHITELIST_FILTER = 1
BLACKLIST_FILTER = 2

MINIMUM_PRIORITY_TO_FETCH_DEFAULT_VALUE = MEDIUM_PRIORITY
TICKETS_CONNECTOR_SUPPORTED_TICKET_TYPES = [INCIDENT_TICKET, SERVICE_REQUEST_TICKET]

DEVICE_VENDOR = "Freshworks"
DEVICE_PRODUCT = "Freshservice"

TICKET_PRIORITY_TO_SIEM_SEVERITY = {
    -1: -1,
    1: 40,
    2: 60,
    3: 80,
    4: 100
}
MINIMUM_TICKET_PRIORITIES = {
    LOW_PRIORITY: [LOW_PRIORITY, MEDIUM_PRIORITY, HIGH_PRIORITY, URGENT_PRIORITY],
    MEDIUM_PRIORITY: [MEDIUM_PRIORITY, HIGH_PRIORITY, URGENT_PRIORITY],
    HIGH_PRIORITY: [HIGH_PRIORITY, URGENT_PRIORITY],
    URGENT_PRIORITY: [URGENT_PRIORITY]
}

PRIVATE_NOTE = "Private"
NOT_CHANGED = "Not Changed"
ALL = "All"
DATE_FORMAT = "%Y-%m-%dT%H:%M:%SZ"

PARAMETERS_DEFAULT_DELIMITER = ', '
CSV_TABLE_DELIMITER = ', '
NEW_LINE = '\n'
DOUBLE_NEW_LINE = '\n\n'

# Error Codes
ACCESS_DENIED = "access_denied"
INVALID_CREDENTIALS = "invalid_credentials"
INVALID_FIELD = "invalid_field"
INVALID_VALUE = "invalid_value"
INVALID_JSON = "invalid_json"
DUPLICATE_VALUE = "duplicate_value"
INVALID_SIZE = "invalid_size"
INPUT_VALIDATION_ERRORS = [INVALID_FIELD, INVALID_VALUE, INVALID_JSON, INVALID_SIZE]
AUTHORIZATION_ERRORS = [ACCESS_DENIED, INVALID_CREDENTIALS]

# Error Fields
TIME_SPENT_FIELD = "time_spent"

LIST_AGENTS_TABLE_NAME = "Freshservice Agents Found"
LIST_REQUESTERS_TABLE_NAME = "Freshservice Requesters Found"

ROWS_PER_PAGE_PARAM_NAME = "Rows per Page"
START_AT_PAGE_PARAM_NAME = "Start at Page"
MAX_ROWS_TO_RETURN_PARAM_NAME = "Max Rows to Return"

# Tickets Closure Job
TICKETS_SYNC_CLOSURE_JOB_NAME = "Freshservice Sync Tickets Closure Job"

# Tickets Conversations Job
TICKETS_SYNC_CONVERSATIONS_JOB_NAME = "Freshservice Sync Tickets Conversations Job"
SIEMPLIFY_COMMENT_PREFIX = "SIEMPLIFY:"
FRESHSERVICE_COMMENT_PREFIX = "Freshservice Comment Sync Job:"
REPLIES = "Replies"
NOTES = "Notes"
CONVERSATION_TYPES = [REPLIES, NOTES]
COMMENT_PRIVATE_NOTE = "Private Note"
COMMENT_PUBLIC_NOTE = "Public Note"
COMMENT_REPLY = "Reply"
SYNC_SIEMPLIFY_COMMENTS_AS_TYPES = [COMMENT_PRIVATE_NOTE, COMMENT_PUBLIC_NOTE, COMMENT_REPLY]
CASE_STATUS_OPEN = 1
FRESHSERVICE_TAG = "Freshservice"

STORED_IDS_LIMIT = 3000
