{
    "CreationTimeUnixTimeInMs": 1518540281258, 
    "Creator": "admin", 
    "Description": "Hunt a domain and retrieve a list of associated tags", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"EntityResult\": [{\"visible\": true, \"_id\": \"8002b33fdf1caec503a25ee39297005e84c6af169df65d8be82e2465baa9b2b0\", \"_source\": {\"malware\": 1, \"sha1\": \"d2884e3655ce4ba167f0083054d2a9ed02669241\", \"create_date\": \"2019-09-20T01:57:15\", \"finish_date\": \"2019-09-20T02:03:48\", \"imphash\": \"ca6f8d49909b618c106e9274d41caec8\", \"filetype\": \"DLL64\", \"ispublic\": 1, \"tag\": [], \"tag_groups\": [], \"tasks\": [{\"metadata_compilation_ts\": \"2019-09-20T07:31:06\"}], \"ssdeep\": \"3072:656zgKIvACBkQTQzhH6ejYF9aIRQkfGRLe0oaf:JtIvNTKhakYF9lRQKPaf\", \"sha256\": \"8002b33fdf1caec503a25ee39297005e84c6af169df65d8be82e2465baa9b2b0\", \"region\": [\"us\"], \"md5\": \"0e1e960c1de792f71b70eb8c8ab47a00\", \"size\": 131072}}], \"Entity\": \"heroisshit.com\"}]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "AutoFocus", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1518540281258, 
    "Name": "Hunt Domain", 
    "Parameters": [], 
    "ScriptResultName": "success", 
    "SimulationDataJson": "{\"Entities\": [\"HOSTNAME\"]}", 
    "Type": 0, 
    "Version": 0.0,
    "IsAsync": true
}