{
    "CreationTimeUnixTimeInMs": 1518539171607, 
    "Creator": "admin", 
    "Description": "Hunt a URL and retrieve a list of associated tags", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"EntityResult\": [{\"visible\": true, \"_id\": \"1a0e60bdaed45635be8dfe2ada5b3897c5346604d9c29df3db6e6e2f7ea5f5fd\", \"_source\": {\"size\": 165888, \"malware\": 0, \"sha1\": \"81bb895a833594013bc74b429fb1f24f9ec9df26\", \"create_date\": \"2019-08-14T23:01:24\", \"finish_date\": \"2019-08-14T23:07:40\", \"imphash\": \"0a38e850afb4bc720ee47a34e25f5b35\", \"filetype\": \"DLL64\", \"ispublic\": 1, \"tasks\": [{\"metadata_compilation_ts\": \"2019-07-30T14:47:02\"}], \"region\": [\"us\"], \"ssdeep\": \"3072:JYS22GGzr5yt8XBlkWj/ld/4Pq+HZk/4mQp39pXdxRvA6ppg+ea:ZIWRd/4PqI41QpTFpg+e\", \"sha256\": \"1a0e60bdaed45635be8dfe2ada5b3897c5346604d9c29df3db6e6e2f7ea5f5fd\", \"tag_groups\": [], \"tag\": [], \"md5\": \"385eab250b3164ef84bb71efca8e305d\"}}], \"Entity\": \"http://heroisshit.com\"}]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "AutoFocus", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1518539171607, 
    "Name": "Hunt Url", 
    "Parameters": [], 
    "ScriptResultName": "success", 
    "SimulationDataJson": "{\"Entities\": [\"DestinationURL\"]}", 
    "Type": 0, 
    "Version": 0.0,
    "IsAsync": true
}