{
    "CreationTimeUnixTimeInMs": 1514460089816, 
    "Creator": "admin", 
    "Description": "Provide security information about a domain (as an attachment)", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"EntityResult\": {\"found\": false, \"popularity\": 0.0, \"geodiversity_normalized\": [], \"dga_score\": -16.878373381058395, \"rip_score\": 0.0, \"asn_score\": 0.0, \"securerank2\": 0.0, \"geoscore\": 0.0, \"attack\": \"\", \"ks_test\": 0.0, \"pagerank\": 0.0, \"geodiversity\": [], \"prefix_score\": 0.0, \"perplexity\": 0.9961472993373601, \"entropy\": 2.2516291673878226, \"fastflux\": false, \"threat_type\": \"\", \"tld_geodiversity\": []}, \"Entity\": \"zahav1.ru\"}]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "CiscoUmbrella", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1514460089816, 
    "Name": "Get Domain Security Info", 
    "Parameters": [], 
    "ScriptResultName": "is_success", 
    "SimulationDataJson": "{\"Entities\": [\"HOSTNAME\"]}", 
    "Type": 0, 
    "Version": 0.0
}