### Json Structure Params ###
json_result_has_entities: no
entity_result_list_path: '[{stepInstanceName}.JsonResult]'
json_result_list: '[{stepInstanceName}.JsonResult]'

### HTML Structure Params ###
main_text_singular: RESULT FOUND
main_text_plural: RESULTS FOUND

import_svg_from_integration: yes

### Table Structure Params ###
auto_map_columns: yes
