{
    "CreationTimeUnixTimeInMs": 1518514906976, 
    "Creator": "admin", 
    "Description": "Block IP addresses in a given policy", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[\"1.1.1.1\", \"2.2.2.2\"]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "PaloAltoPanorama", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1518514906976, 
    "Name": "Block ips in policy", 
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1520155635793, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Specify name of the device. The default device name for Palo Alto Panorama is localhost.localdomain. Visit action documentation to get more insights on where you can find this value.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1520155635793, 
            "Name": "Device Name", 
            "Type": 0, 
            "Value": ""
        }, 
        {
            "CreationTimeUnixTimeInMs": 1520155635793, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Specify name of the device group. Visit action documentation to get more insights on where you can find this value.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1520155635793, 
            "Name": "Device Group Name", 
            "Type": 0, 
            "Value": ""
        }, 
        {
            "CreationTimeUnixTimeInMs": 1520155635793, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Specify name of the policy.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1520155635793, 
            "Name": "Policy Name", 
            "Type": 0, 
            "Value": ""
        }, 
        {
            "CreationTimeUnixTimeInMs": 1520155635793, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Specify what should be the target. Possible values: source, destination.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1520155635793, 
            "Name": "Target", 
            "Type": 0, 
            "Value": ""
        }
    ], 
    "ScriptResultName": "success", 
    "SimulationDataJson": "{\"Entities\": [\"ADDRESS\"]}", 
    "Type": 0, 
    "Version": 0.0
}