### Json Structure Params ###
json_result_has_entities: yes
entity_result_list_path: EntityResult

### HTML Structure Params ###
main_text_singular: SIMILAR DEVICE FOUND
main_text_plural: SIMILAR DEVICES FOUND

import_svg_from_integration: yes

### Table Structure Params ###
table_data:
  - header: Hostname
    value:
      keys_to_display:
        - hostname

  - header: IP
    value:
      keys_to_display:
        - ip

  - header: OS
    value:
      keys_to_display:
        - os

  - header: Score
    value:
      keys_to_display:
        - score

  - header: Type
    value:
      keys_to_display:
        - typelabel

  - header: Device Label
    value:
      keys_to_display:
        - devicelabel