# Action Script Names
PAUSE_ALERT_SLA_SCRIPT_NAME = "Pause Alert SLA"
RESUME_ALERT_SLA_SCRIPT_NAME = "Resume Alert SLA"
REMOVE_TAG_SCRIPT_NAME = u"Remove Tag"
UPDATE_CASE_DESC_SCRIPT_NAME = u"Update Case Description"
SET_CONTEXT_VALUE_SCRIPT_NAME = u"Set Context Value"
GET_CONTEXT_VALUE_SCRIPT_NAME = u"Get Context Value"
GET_CONNECTOR_CONTEXT_VALUE_SCRIPT_NAME = u"Get Connector Context Value"
SET_CASE_SLA_SCRIPT_NAME = "Set Case SLA"
SET_ALERT_SLA_SCRIPT_NAME = "Set Alert SLA"

PAUSE_ALERT_SLA_MIN_SIEMPLIFY_VERSION_SUPPORTED = "5.6.1"
RESUME_ALERT_SLA_MIN_SIEMPLIFY_VERSION_SUPPORTED = "5.6.1"

# Siemplify Endpoints
SIEMPLIFY_ENDPOINTS = {
    "pause_alert_sla": "external/v1/cases/PauseAlertSla",
    "resume_alert_sla": "external/v1/cases/ResumeAlertSla"
}


GLOBAL_CONTEXT = 0
CONNECTOR_CONTEXT = 4
GLOBAL_CONTEXT_IDENTIFIER = "GLOBAL"
CONTEXT_CHARACTERS_LIMIT = 5000
CONTEXT_TABLE_NAME = " Context Values for scope {}"
CONNECTOR_CONTEXT_TABLE_NAME = "Available Connector Context Values"

MAX_DELIMITER_SIZE = 64

# System notification Ids
SDK_JOB_ACTIONS_PLAYBOOK_ACTIONS_ERRORS = 'SDK_JOB_ACTIONS_PLAYBOOK_ACTIONS_ERRORS'
SDK_CASES_COLLECTOR_PACKAGE_PROCESS_ERROR = 'SDK_CASES_COLLECTOR_PACKAGE_PROCESS_ERROR'
SDK_CASES_COLLECTOR_ERROR = 'SDK_CASES_COLLECTOR_ERROR'
SDK_JOB_CONNECTORS_ALERT_DIGESTION_ERRORS = 'SDK_JOB_CONNECTORS_ALERT_DIGESTION_ERRORS'
SDK_JOB_ETL_ALERT_DIGESTION_ERRORS = 'SDK_JOB_ETL_ALERT_DIGESTION_ERRORS'
SDK_JOB_JOBS_ERRORS = 'SDK_JOB_JOBS_ERRORS'
SDK_JOB_MACHINE_RESOURCE = 'SDK_JOB_MACHINE_RESOURCE'
