INTEGRATION_NAME = "McAfeeATD"
INTEGRATION_DISPLAY_NAME = "McAfee ATD"

# Actions
PING_SCRIPT_NAME = "{} - Ping".format(INTEGRATION_DISPLAY_NAME)
CHECK_HASH_SCRIPT_NAME = "{} - Check Hash".format(INTEGRATION_DISPLAY_NAME)
GET_ANALYZER_PROFILES_SCRIPT_NAME = "{} - Get Analyzer Profiles".format(INTEGRATION_DISPLAY_NAME)
GET_REPORT_SCRIPT_NAME = "{} - Get Report".format(INTEGRATION_DISPLAY_NAME)
SUBMIT_FILE_SCRIPT_NAME = "{} - Submit File".format(INTEGRATION_DISPLAY_NAME)
SUBMIT_URL_SCRIPT_NAME = "{} - Submit URL".format(INTEGRATION_DISPLAY_NAME)
