{
    "CreationTimeUnixTimeInMs": 1518362714597,
    "Creator": "admin",
    "Description": "Test Connectivity. Requires: IMAP or SMTP configuration",
    "Id": -1,
    "IntegrationIdentifier": "EmailV2",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1518362714597,
    "Name": "Ping",
    "Parameters": [],
    "ScriptResultName": "is_succeed",
    "Version": 1.0,
    "SimulationDataJson": "{\"Entities\": []}"
}