INTEGRATION_IDENTIFIER = "GoogleGKE"
INTEGRATION_DISPLAY_NAME = "Google Kubernetes Engine"

API_URL = "https://container.googleapis.com"
OAUTH_SCOPES = ["https://www.googleapis.com/auth/cloud-platform"]

# Actions
PING_SCRIPT_NAME = "Ping"
LIST_CLUSTERS_SCRIPT_NAME = "List Clusters"
SET_CLUSTER_LABELS_SCRIPT_NAME = "Set Cluster Labels"
SET_CLUSTER_ADDONS_SCRIPT_NAME = "Set Cluster Addons"
LIST_NODE_POOLS_SCRIPT_NAME = "List Node Pools"
SET_NODE_AUTOSCALING_SCRIPT_NAME = "Set Node Autoscaling"
SET_NODE_POOL_MANAGEMENT_SCRIPT_NAME = "Set Node Pool Management"
SET_NODE_POOL_COUNT_SCRIPT_NAME = "Set Node Count"
LIST_OPERATIONS_SCRIPT_NAME = "List Operations"
GET_OPERATION_STATUS_SCRIPT_NAME = "Get Operation Status"

ALL_CLUSTERS = "-"
NOT_SPECIFIED = "Not Specified"
COMMA_SPACE = ", "

# Operation
RUNNING = "RUNNING"
PENDING = "PENDING"
STATUS_UNSPECIFIED = "STATUS_UNSPECIFIED"
DONE = "DONE"
ABORTING = "ABORTING"
IN_PROGRESS_STATUSES = [PENDING, RUNNING]

# Params
NOT_CHANGED = "Not Changed"
DISABLED = "Disabled"
ENABLED = "Enabled"
ENABLED_LOAD_BALANCER_UNSPECIFIED = "Enabled, Load Balancer Type Unspecified"
ENABLED_LOAD_BALANCER_EXTERNAL = "Enabled, Load Balancer Type External"
ENABLED_LOAD_BALANCER_INTERNAL = "Enabled, Load Balancer Type Internal"

# Cluster AddonsConfig
LOAD_BALANCER_TYPE_UNSPECIFIED = "LOAD_BALANCER_TYPE_UNSPECIFIED"
LOAD_BALANCER_TYPE_EXTERNAL = "LOAD_BALANCER_TYPE_EXTERNAL"
LOAD_BALANCER_TYPE_INTERNAL = "LOAD_BALANCER_TYPE_INTERNAL"

MAP_CLOUD_RUN_CONFIG_PARAMS = {  # first value is whether cloud run config should be disabled, second value is load balancer type
    DISABLED: (True, None),
    ENABLED_LOAD_BALANCER_UNSPECIFIED: (False, LOAD_BALANCER_TYPE_UNSPECIFIED),
    ENABLED_LOAD_BALANCER_EXTERNAL: (False, LOAD_BALANCER_TYPE_EXTERNAL),
    ENABLED_LOAD_BALANCER_INTERNAL: (False, LOAD_BALANCER_TYPE_INTERNAL)
}

# Error Codes
INVALID_ARGUMENT = "INVALID_ARGUMENT"
NOT_FOUND = "NOT_FOUND"
PERMISSION_DENIED = "PERMISSION_DENIED"
PROJECT_LOOKUP_ERROR_MESSAGE = "Project lookup error"
LOCATION_ERROR_MESSAGE = ["Location", "does not exist"]
NODE_POOL_ERROR_MESSAGE = ["Node pool", "not found"]

ASYNC_ACTION_TIMEOUT_THRESHOLD_MS = 40 * 1000
