{
    "CreationTimeUnixTimeInMs": 1509263483089, 
    "Creator": "admin", 
    "Description": "Enrich a Hash using Digital Shadows information.", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[ { \"EntityResult\": { \"content\": [ { \"type\": \"CYLANCE_FILE_HASH\", \"entity\": { \"status\": 0, \"fileHashInfo\": { \"status\": \"COMPLETE\", \"hashes\": { \"sha256\": \"617F7301FD67E8B5D8AD42D4E94E02CB313FE5AD51770EF93323C6115E52FE98\", \"md5\": \"8FE94843A3E655209C57AF587849AC3A\", \"sha1\": \"CF0743ED381ADE69BBA3D1DD3D357A8300BCD4AE\" }, \"generalScore\": -1, \"classifiers\": { \"ml\": 1, \"industry\": -1, \"human\": -1 }, \"statusCode\": 1 }, \"requestedHash\": \"617f7301fd67e8b5d8ad42d4e94e02cb313fe5ad51770ef93323c6115e52fe98\" } } ] }, \"Entity\": \"617f7301fd67e8b5d8ad42d4e94e02cb313fe5ad51770ef93323c6115e52fe98\" } ]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "DigitalShadows", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1509263483089, 
    "Name": "EnrichHash", 
    "Parameters": [], 
    "Script": "", 
    "ScriptResultName": "is_success", 
    "SimulationDataJson": "{\"Entities\": [\"FILEHASH\"]}", 
    "Type": 0, 
    "Version": 0.0
}