{
    "CreationTimeUnixTimeInMs": 1570446244, 
    "Creator": "admin", 
    "Description": "Disable account in Azure Active Directory. Action expects Siemplify user entity in username@domain format.",
    "Id": -1, 
    "IntegrationIdentifier": "AzureActiveDirectory", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1570446244, 
    "Name": "Disable Account", 
    "ScriptResultName": "is_success", 
    "SimulationDataJson": "{\"Entities\": [\"USERUNIQNAME\"]}", 
    "Type": 0, 
    "Version": 1.0
}