{
    "CreationTimeUnixTimeInMs": 1570446244, 
    "Creator": "admin", 
    "Description": "Force password update for user so the user will have to change their password on next login. Action expects Siemplify user entity in username@domain format.",
    "Id": -1,
    "IntegrationIdentifier": "AzureActiveDirectory", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1570446244, 
    "Name": "Force Password Update", 
    "ScriptResultName": "is_success", 
    "SimulationDataJson": "{\"Entities\": [\"USERUNIQNAME\"]}", 
    "Type": 0, 
    "Version": 1.0
}