{
    "CreationTimeUnixTimeInMs": 1570446244, 
    "Creator": "admin", 
    "Description": "Get manager contact details for user. Action expects Siemplify user entity in username@domain format.",
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"EntityResult\": {\"displayName\": \"manager@mail.com\", \"mobilePhone\": \"1212-12312-123\",\"@odata.context\": \"graph.microsoft.com\"}, \"Entity\": \"user@mail.com\"}]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "AzureActiveDirectory", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1570446244, 
    "Name": "Get Manager Contact Details", 
    "ScriptResultName": "is_success", 
    "SimulationDataJson": "{\"Entities\": [\"USERUNIQNAME\"]}", 
    "Type": 0, 
    "Version": 1.0
}