{
    "CreationTimeUnixTimeInMs": 1570446244,
    "Creator": "admin",
    "Description": "List Azure Active Directory groups based on the specified search criteria. Note that action is not working on Siemplify entities. Additionally, filtering is working on the Name field.",
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"Group_Type\": \"managed\", \"Id\": \"1212-12312-123\",\"Name\": \"Group Name\",\"Description\": \"This group is ...\", \"Created_Time\":\"2019-10-24T19:10:18Z\"}]",
            "ResultName": "JsonResult"
        }
    ],
    "Id": -1,
    "IntegrationIdentifier": "AzureActiveDirectory",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1570446244,
    "Name": "List Groups",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1570446244,
            "CustomActionId": -1,
            "DefaultValue": "ASC",
            "Description": "Specifies the result order. Groups are sorted by their display name.",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1570446244,
            "Name": "Order By",
            "Value": "ASC",
            "Type": 15,
            "OptionalValues": [
                "DESC",
                "ASC"
            ]
        },
        {
            "CreationTimeUnixTimeInMs": 1560351300835,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify max number of groups to return.",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1560351300835,
            "Name": "Results Limit",
            "OptionalValues": null,
            "OptionalValuesJson": null,
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1570446244,
            "CustomActionId": -1,
            "DefaultValue": "Equal",
            "Description": "Specify what filter logic should be applied. Filtering is working on the Name field.",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1570446244,
            "Name": "Filter Logic",
            "Value": "Equal",
            "Type": 15,
            "OptionalValues": [
                "Equal",
                "Contains"
            ]
        },
        {
            "CreationTimeUnixTimeInMs": 1560351300835,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify what value should be used in the filter. If “Equal“ is selected, action will try to find the exact match among results and if “Contains“ is selected, action will try to find results that contain that substring. If nothing is provided in this parameter, the filter will not be applied. Filtering is working on the Name field.",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1560351300835,
            "Name": "Filter Value",
            "OptionalValues": null,
            "OptionalValuesJson": null,
            "Type": 0,
            "Value": ""
        }
    ],
    "ScriptResultName": "is_success",
    "Type": 0,
    "Version": 1.0,
    "SimulationDataJson": "{\"Entities\":[]}"
}