{
    "CreationTimeUnixTimeInMs": 1570446244, 
    "Creator": "admin", 
    "Description": "Change user password to the password specified in the action. User will have to change their password on next login. Action expects Siemplify user entity in username@domain format.",
    "Id": -1, 
    "IntegrationIdentifier": "AzureActiveDirectory", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1570446244, 
    "Name": "Reset User Password", 
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1570446244, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "User Authentication password.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1570446244, 
            "Name": "Password", 
            "Type": 12, 
            "Value": ""
        }
    ], 
    "ScriptResultName": "is_success", 
    "SimulationDataJson": "{\"Entities\": [\"USERUNIQNAME\"]}", 
    "Type": 0, 
    "Version": 1.0
}