from docx import shared

DOCUMENT_FONT = 'Arial'
DOCUMENT_TEXT_COLOR = shared.RGBColor(0x0, 0x0, 0x0)  # BLACK

DOCUMENT_TITLE_FONT_SIZE = 18
IS_DOCUMENT_TITLE_BOLD = True
IS_DOCUMENT_TITLE_UNDERLINED = False

PUBLISH_DATE_FONT_SIZE = 11
IS_PUBLISH_DATE_BOLD = False
IS_PUBLISH_DATE_UNDERLINED = False

TECH_DETAILS_TITLE_FONT_SIZE = 16
IS_TECH_DETAILS_TITLE_BOLD = True
IS_TECH_DETAILS_TITLE_UNDERLINED = True

TECH_DETAILS_TEXT_FONT_SIZE = 11
IS_TECH_DETAILS_TEXT_UNDERLINED = False

MAIN_BODY_TITLE_FONT_SIZE = 18
IS_MAIN_BODY_BOLD = True
IS_MAIN_BODY_UNDERLINED = False
