{
    "CreationTimeUnixTimeInMs": 1520162690870,
    "Creator": "admin",
    "Description": "Get event logs by its blocking ID",
    "Id": -1,
    "IntegrationIdentifier": "F5BigIQ",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1520162690870,
    "Name": "Get Event Logs By Blocking ID",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1520179480674,
            "CustomActionId": -1,
            "DefaultValue": null,
            "Description": "",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1520179480674,
            "Name": "Blocking ID",
            "Type": 0,
            "Value": ""
        }
    ],
    "ScriptResultName": "is_success",
    "Type": 0,
    "Version": 0.0,
    "SimulationDataJson": "{\"Entities\": []}"
}