{
    "CreationTimeUnixTimeInMs": 1570446244,
    "Creator": "admin",
    "Description": "Test connectivity to the SonicWall with parameters provided at the integration configuration page on the Marketplace tab.",
    "Id": -1,
    "IntegrationIdentifier": "SonicWall-Beta",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1570446244,
    "Name": "Ping",
    "Parameters": [],
    "ScriptResultName": "is_success",
    "Type": 0,
    "Version": 1.0,
    "SimulationDataJson": "{\"Entities\": []}"
}