{
    "CreationTimeUnixTimeInMs": 1519138520857,
    "Creator": "admin",
    "Description": "Get the list of installed services on the system",
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"DisplayName\": \"Adobe Flash Player Update Service\", \"ServiceSpecificExitCode\": 0, \"State\": \"Stopped\", \"SystemName\": \"PC-01\", \"ErrorControl\": \"Normal\", \"Status\": \"OK\", \"ProcessId\": 0, \"DesktopInteract\": false, \"Started\": false, \"AcceptStop\": false, \"CheckPoint\": 0, \"PathName\": \"C:\\\\Windows\\\\SysWOW64\\\\Macromed\\\\Flash\\\\FlashPlayerUpdateService.exe\", \"WaitHint\": 0, \"Name\": \"AdobeFlashPlayerUpdateSvc\", \"InstallDate\": null, \"Caption\": \"Adobe Flash Player Update Service\", \"StartMode\": \"Manual\", \"Description\": \"This service keeps your Adobe Flash Player installation up to date with the latest enhancements and security fixes.\", \"ServiceType\": \"Own Process\", \"TagId\": 0, \"DelayedAutoStart\": false, \"StartName\": \"LocalSystem\", \"AcceptPause\": false, \"CreationClassName\": \"Win32_Service\", \"SystemCreationClassName\": \"Win32_ComputerSystem\", \"ExitCode\": 0}]",
            "ResultName": "JsonResult"
        }
    ],
    "Id": -1,
    "IntegrationIdentifier": "WMI",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1519138520857,
    "Name": "ListServices",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1519140336195,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1519140336195,
            "Name": "Server Address",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1519140336195,
            "CustomActionId": -1,
            "DefaultValue": null,
            "Description": "",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1519140336195,
            "Name": "Username",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1519140336195,
            "CustomActionId": -1,
            "DefaultValue": null,
            "Description": "",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1519140336195,
            "Name": "Password",
            "Type": 12,
            "Value": ""
        }
    ],
    "ScriptResultName": "services",
    "Type": 0,
    "Version": 0.0,
    "SimulationDataJson": "{\"Entities\": []}"
}