INTEGRATION_NAME = 'CSV'
DEFAULT_PRODUCT = DEFAULT_VENDOR = INTEGRATION_NAME
# ACTIONS NAMES
PING_SCRIPT_NAME = '{} - Ping'.format(INTEGRATION_NAME)
SEARCH_BY_STRING_SCRIPT_NAME = '{} - Search by String'.format(INTEGRATION_NAME)
SEARCH_BY_ENTITY_SCRIPT_NAME = '{} - Search by Entity'.format(INTEGRATION_NAME)


# CONNECTORS NAMES
CSV_CONNECTOR_SCRIPT_NAME = 'CSV connector'

# TABLE NAMES
RECORDS_TABLE_NAME = '{} Found Records'


# PREFIXES
ENRICHMENT_PREFIX = "CSVEnrichment"


# INSIGHTS
FOUND_IN_CSV_INSIGHT_NAME = 'Found in CSV: {}'
