{
    "CreationTimeUnixTimeInMs": 1513759800431, 
    "Creator": "admin", 
    "Description": "Block a URL in WebSense API category", 
    "Id": -1, 
    "IntegrationIdentifier": "Websense", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1513759800431, 
    "Name": "Block Url API", 
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1513763793053, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "The API manage category name.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1513763793053, 
            "Name": "CategoryName", 
            "Type": 0, 
            "Value": ""
        }, 
        {
            "CreationTimeUnixTimeInMs": 1513763793053, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "The URLs to block, comma separated.", 
            "Id": -1, 
            "IsMandatory": false, 
            "ModificationTimeUnixTimeInMs": 1513763793053, 
            "Name": "Urls", 
            "Type": 0, 
            "Value": ""
        }
    ], 
    "Script": "from SiemplifyAction import *\nfrom WebsenseManager import WebsenseAPIManager\n\ndef main():\n\tsiemplify = SiemplifyAction()\n\toutput_message = 'Error accured'\n\tresult_value = 'False'\n\tconf = siemplify.get_configuration('Websense')\n\t\n\twebsense_manager = WebsenseAPIManager(conf['ApiRoot'], conf['GatewayUser'], conf['GatewayPassword'])\n\turl = siemplify.parameters['Url']\n\tcategory = siemplify.parameters['CategoryName']\n\tresult = websense_manager.add_url_to_category(url, category)\n\n\tif result:\n\t\toutput_message = 'Url:{0} added to category:{1}'.format(url, category)\n\t\tresult_value = 'true'\n\t\n\tsiemplify.end(output_message, result_value)\n\t\n\nif __name__ == \"__main__\":\n\tmain()", 
    "ScriptResultName": "is_success", 
    "SimulationDataJson": "{\"Entities\": [\"DestinationURL\"]}", 
    "Type": 0, 
    "Version": 2.0
}