{
    "CreationTimeUnixTimeInMs": 1517341271876,
    "Creator": "admin",
    "Description": "Test connectivity to Microsoft SCCM instance with parameters provided at the integration configuration page on Marketplace tab.",
    "Id": -1,
    "IntegrationIdentifier": "SCCM",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1517341271876,
    "Name": "Ping",
    "Parameters": [],
    "ScriptResultName": "is_succeed",
    "Type": 0,
    "Version": 0.0,
    "SimulationDataJson": "{\"Entities\": []}"
}