{
    "CreationTimeUnixTimeInMs": 1515073753262, 
    "Creator": "admin", 
    "Description": "Create an adversary in ThreatQ.", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "{\"tip1@siemplify.com\": {\"updated_at\": \"2020-07-30 09:48:36\", \"created_at\": \"2020-07-30 09:48:36\", \"id\": 19, \"name\": \"tip1@siemplify.com\"}, \"tip2@siemplify.com\": {\"updated_at\": \"2020-07-30 09:48:36\", \"created_at\": \"2020-07-30 09:48:36\", \"id\": 20, \"name\": \"tip2@siemplify.com\"}}", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "ThreatQ", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1515073753262, 
    "Name": "Create Adversary", 
    "Parameters": [], 
    "ScriptResultName": "is_success", 
    "SimulationDataJson": "{\"Entities\": [\"USERUNIQNAME\"]}", 
    "Type": 0, 
    "Version": 0.0
}