{
    "CreationTimeUnixTimeInMs": 1515073753262,
    "Creator": "admin",
    "Description": "Action links two objects in ThreatQ.",
    "DynamicResultsMetadata": [
        {
            "ResultExample": "{\"id\":2,\"value\":\"123123\",\"status_id\":null,\"type_id\":null,\"description\":null,\"started_at\":\"2020-07-20 12:27:00\",\"ended_at\":\"2020-07-20 12:27:00\",\"created_at\":\"2020-07-20 12:27:10\",\"updated_at\":\"2020-07-20 12:27:10\",\"touched_at\":\"2020-07-20 14:50:14\",\"object_id\":4,\"object_code\":\"incident\",\"object_name\":\"Incident\",\"object_name_plural\":\"Incidents\",\"pivot\":{\"id\":18,\"created_at\":\"2020-07-20 14:50:14\",\"updated_at\":\"2020-07-20 14:50:14\"}}",
            "ResultName": "JsonResult"
        }
    ],
    "Id": -1,
    "IntegrationIdentifier": "ThreatQ",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1515073753262,
    "Name": "Link Objects",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1515073753262,
            "CustomActionId": -1,
            "DefaultValue": "Adversary",
            "Description": "Specify the type of the source object.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1515073753262,
            "Name": "Source Object Type",
            "Type": 15,
            "OptionalValues": [
                "Adversary",
                "Attack Pattern",
                "Campaign",
                "Course of Action",
                "Event",
                "Exploit Target",
                "File",
                "Identity",
                "Incident",
                "Indicator",
                "Intrusion Set",
                "Malware",
                "Report",
                "Signature",
                "Task",
                "Tool",
                "TTP",
                "Vulnerability"
            ],
            "Value": "Adversary"
        },
        {
            "CreationTimeUnixTimeInMs": 1515073753262,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify identifier of the source object. For example, it can be an MD5 hash, title of the event, name of the adversary etc.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1515073753262,
            "Name": "Source Object Identifier",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1515073753262,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify the type of the source indicator. This parameter is only used, if Source Object Type is Indicator.",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1515073753262,
            "Name": "Source Indicator Type",
            "Type": 15,
            "OptionalValues": [
                "ASN",
                "Binary String",
                "CIDR Block",
                "CVE",
                "Email Address",
                "Email Attachment",
                "Email Subject",
                "File Mapping",
                "File Path",
                "File name",
                "FQDN",
                "Fuzzy Hash",
                "GOST Hash",
                "Hash ION",
                "IPv4 Address",
                "IPv6 Address",
                "MAC Address",
                "MD5",
                "Mutex",
                "Password",
                "Registry Key",
                "Service Name",
                "SHA-1",
                "SHA-256",
                "SHA-384",
                "SHA-512",
                "String",
                "x509 Serial",
                "x509 Subject",
                "URL",
                "URL Path",
                "User-agent",
                "Username",
                "X-Mailer"
            ],
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1515073753262,
            "CustomActionId": -1,
            "DefaultValue": "Adversary",
            "Description": "Specify the type of the destination object.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1515073753262,
            "Name": "Destination Object Type",
            "Type": 15,
            "OptionalValues": [
                "Adversary",
                "Attack Pattern",
                "Campaign",
                "Course of Action",
                "Event",
                "Exploit Target",
                "File",
                "Identity",
                "Incident",
                "Indicator",
                "Intrusion Set",
                "Malware",
                "Report",
                "Signature",
                "Task",
                "Tool",
                "TTP",
                "Vulnerability"
            ],
            "Value": "Adversary"
        },
        {
            "CreationTimeUnixTimeInMs": 1515073753262,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify identifier of the destination object. For example, it can be an MD5 hash, title of the event, name of the adversary etc.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1515073753262,
            "Name": "Destination Object Identifier",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1515073753262,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify the type of the destination indicator. This parameter is only used, if Destination Object Type is Indicator.",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1515073753262,
            "Name": "Destination Indicator Type",
            "Type": 15,
            "OptionalValues": [
                "ASN",
                "Binary String",
                "CIDR Block",
                "CVE",
                "Email Address",
                "Email Attachment",
                "Email Subject",
                "File Mapping",
                "File Path",
                "File name",
                "FQDN",
                "Fuzzy Hash",
                "GOST Hash",
                "Hash ION",
                "IPv4 Address",
                "IPv6 Address",
                "MAC Address",
                "MD5",
                "Mutex",
                "Password",
                "Registry Key",
                "Service Name",
                "SHA-1",
                "SHA-256",
                "SHA-384",
                "SHA-512",
                "String",
                "x509 Serial",
                "x509 Subject",
                "URL",
                "URL Path",
                "User-agent",
                "Username",
                "X-Mailer"
            ],
            "Value": ""
        }
    ],
    "ScriptResultName": "is_success",
    "Type": 0,
    "Version": 0.0
}