{
    "CreationTimeUnixTimeInMs": 1515073753262,
    "Creator": "admin",
    "Description": "Action lists related objects in ThreatQ.",
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"last_detected_at\": null, \"hash\": \"12fc1985a0ab5984cb70385004f32ffa\", \"description\": null, \"status_id\": 4, \"created_at\": \"2020-07-30 12:25:54\", \"type_id\": 18, \"expires_needs_calc\": \"N\", \"updated_at\": \"2020-07-30 12:25:54\", \"value\": \"8c71fb3f7593543f2ad180d31148a7cf\", \"sync_hash\": \"68430f34910adb87797ca0df95354393\", \"touched_at\": \"2020-08-03 07:18:31\", \"class\": \"host\", \"expires_calculated_at\": \"2020-08-03 07:20:02\", \"expires_at\": null, \"pivot\": {\"src_object_id\": 19, \"created_at\": \"2020-08-03 07:18:31\", \"updated_at\": \"2020-08-03 07:18:31\", \"dest_object_id\": 71, \"src_type\": \"adversary\", \"dest_type\": \"indicator\", \"id\": 28}, \"deleted_at\": null, \"id\": 71, \"expired_at\": null}]",
            "ResultName": "JsonResult"
        }
    ],
    "Id": -1,
    "IntegrationIdentifier": "ThreatQ",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1515073753262,
    "Name": "List Related Objects",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1515073753262,
            "CustomActionId": -1,
            "DefaultValue": "Adversary",
            "Description": "Specify the type of the source object.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1515073753262,
            "Name": "Source Object Type",
            "Type": 15,
            "OptionalValues": [
                "Adversary",
                "Attack Pattern",
                "Campaign",
                "Course of Action",
                "Event",
                "Exploit Target",
                "File",
                "Identity",
                "Incident",
                "Indicator",
                "Intrusion Set",
                "Malware",
                "Report",
                "Signature",
                "Task",
                "Tool",
                "TTP",
                "Vulnerability"
            ],
            "Value": "Adversary"
        },
        {
            "CreationTimeUnixTimeInMs": 1515073753262,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify identifier of the source object. For example, it can be an MD5 hash, title of the event, name of the adversary etc.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1515073753262,
            "Name": "Source Object Identifier",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1515073753262,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify the type of the source indicator. This parameter is only used, if Source Object Type is Indicator.",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1515073753262,
            "Name": "Source Indicator Type",
            "Type": 15,
            "OptionalValues": [
                "ASN",
                "Binary String",
                "CIDR Block",
                "CVE",
                "Email Address",
                "Email Attachment",
                "Email Subject",
                "File Mapping",
                "File Path",
                "File name",
                "FQDN",
                "Fuzzy Hash",
                "GOST Hash",
                "Hash ION",
                "IPv4 Address",
                "IPv6 Address",
                "MAC Address",
                "MD5",
                "Mutex",
                "Password",
                "Registry Key",
                "Service Name",
                "SHA-1",
                "SHA-256",
                "SHA-384",
                "SHA-512",
                "String",
                "x509 Serial",
                "x509 Subject",
                "URL",
                "URL Path",
                "User-agent",
                "Username",
                "X-Mailer"
            ],
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1515073753262,
            "CustomActionId": -1,
            "DefaultValue": "Adversary",
            "Description": "Specify the type of the related object that needs to be returned.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1515073753262,
            "Name": "Related Object Type",
            "Type": 15,
            "OptionalValues": [
                "Adversary",
                "Attack Pattern",
                "Campaign",
                "Course of Action",
                "Event",
                "Exploit Target",
                "File",
                "Identity",
                "Incident",
                "Indicator",
                "Intrusion Set",
                "Malware",
                "Report",
                "Signature",
                "Task",
                "Tool",
                "TTP",
                "Vulnerability"
            ],
            "Value": "Adversary"
        },
        {
            "CreationTimeUnixTimeInMs": 1515073753262,
            "CustomActionId": -1,
            "DefaultValue": 50,
            "Description": "Specify how many related objects to return.",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1515073753262,
            "Name": "Max Related Objects To Return",
            "Type": 0,
            "Value": 50
        }
    ],
    "ScriptResultName": "is_success",
    "Type": 0,
    "Version": 0.0
}