{
    "CreationTimeUnixTimeInMs": 1517322230474, 
    "Creator": "admin", 
    "Description": "Blocks a particular hash on endpoints", 
    "Id": -1, 
    "IntegrationIdentifier": "SEP", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1517322230474, 
    "Name": "BlockHash", 
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1519119182120, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "The black list name to add the hash to", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1519119182120, 
            "Name": "Black List Name", 
            "Type": 0, 
            "Value": ""
        }
    ], 
    "ScriptResultName": "success", 
    "SimulationDataJson": "{\"Entities\": [\"FILEHASH\"]}", 
    "Type": 0, 
    "Version": 0.0
}