{
    "CreationTimeUnixTimeInMs": 1517319270272, 
    "Creator": "admin", 
    "Description": "Quarantine an endpoint", 
    "Id": -1, 
    "IntegrationIdentifier": "SEP", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1517319270272, 
    "Name": "QuarantineEndpoint", 
    "Parameters": [], 
    "ScriptResultName": "success", 
    "SimulationDataJson": "{\"Entities\": [\"HOSTNAME\", \"ADDRESS\"]}", 
    "Type": 0, 
    "Version": 0.0
}