{
    "CreationTimeUnixTimeInMs": 1517320188355, 
    "Creator": "admin", 
    "Description": "Scan an endpoint", 
    "Id": -1, 
    "IntegrationIdentifier": "SEP12", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1517320188355, 
    "Name": "ScanEndpoint", 
    "Parameters": [], 
    "ScriptResultName": "success", 
    "SimulationDataJson": "{\"Entities\": [\"HOSTNAME\", \"ADDRESS\"]}", 
    "Type": 0, 
    "Version": 0.0
}