{
    "CreationTimeUnixTimeInMs": 1519822886550, 
    "Creator": "admin", 
    "Description": "List processes by device", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"EntityResult\": {\"0\": {\"applicationName\": \"chrome.exe\", \"processId\": 1234, \"numEvents\": 111, \"applicationPath\": null, \"privatePid\": \"3052-1489181082476-30\", \"sha256Hash\": \"9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08\"}}, \"Entity\": \"HP-01\"}]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "CBDefense", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1519822886550, 
    "Name": "Get Processes", 
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1519823687190, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Timeframe of the search. e.g. 3h", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1519823687190, 
            "Name": "Timeframe", 
            "Type": 0, 
            "Value": ""
        }
    ], 
    "ScriptResultName": "success", 
    "SimulationDataJson": "{\"Entities\": [\"HOSTNAME\", \"ADDRESS\"]}", 
    "Type": 0, 
    "Version": 0.0
}