{
    "CreationTimeUnixTimeInMs": 1507021403986,
    "Creator": "admin",
    "Description": "Check case time according to a given time condition",
    "Id": -1,
    "IntegrationIdentifier": "Siemplify",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1507021403986,
    "Name": "Permitted Alert Time",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1524727455781,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Start of the timeframe, when alerts are allowed. For example: 9:55:24",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1524727455781,
            "Name": "Permitted Start Time",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1524727455781,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "End of the timeframe, when alerts are allowed. For example: 17:23:21",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1524727455781,
            "Name": "Permitted End Time",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1524727455781,
            "CustomActionId": -1,
            "DefaultValue": "false",
            "Description": "",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1524727455781,
            "Name": "Monday",
            "Type": 1,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1524727455781,
            "CustomActionId": -1,
            "DefaultValue": "true",
            "Description": "",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1524727455781,
            "Name": "Tuesday",
            "Type": 1,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1524727455781,
            "CustomActionId": -1,
            "DefaultValue": "true",
            "Description": "",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1524727455781,
            "Name": "Wednesday",
            "Type": 1,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1524727455781,
            "CustomActionId": -1,
            "DefaultValue": "false",
            "Description": "",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1524727455781,
            "Name": "Thursday",
            "Type": 1,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1524727455781,
            "CustomActionId": -1,
            "DefaultValue": "false",
            "Description": "",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1524727455781,
            "Name": "Friday",
            "Type": 1,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1524727455781,
            "CustomActionId": -1,
            "DefaultValue": "false",
            "Description": "",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1524727455781,
            "Name": "Saturday",
            "Type": 1,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1524727455781,
            "CustomActionId": -1,
            "DefaultValue": "false",
            "Description": "",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1524727455781,
            "Name": "Sunday",
            "Type": 1,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1524727455781,
            "CustomActionId": -1,
            "DefaultValue": "UTC",
            "Description": "Timezone name. For example: UTC",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1524727455781,
            "Name": "Input Timezone",
            "Type": 0,
            "Value": ""
        }
    ],
    "ScriptResultName": "Permitted",
    "Type": 0,
    "Version": 0.0,
    "SimulationDataJson": "{\"Entities\": []}"
}