INTEGRATION_NAME = "Twilio"
PING_ACTION = '{} - Ping'.format(INTEGRATION_NAME)
SEND_SMS_ACTION = '{} - SendSMS'.format(INTEGRATION_NAME)
SEND_SMS_AND_WAIT_ACTION = '{} - Send SMS and Wait'.format(INTEGRATION_NAME)
ID_GENERATION_START = 10_000
ID_GENERATION_END = 999_999
