### Json Structure Params ###
json_result_has_entities: no
entity_result_list_path: '[{stepInstanceName}.JsonResult]'
json_result_list: '[{stepInstanceName}.JsonResult]'

### HTML Structure Params ###
main_text_singular: GROUP MEMBER FOUND
main_text_plural: GROUP MEMBERS FOUND

import_svg_from_integration: yes

### Table Structure Params ###
table_data:
  - header: Status
    value:
      keys_to_display:
        - status

  - header: Email
    value:
      keys_to_display:
        - email

  - header: Role
    value:
      keys_to_display:
        - role

  - header: Type
    value:
      keys_to_display:
        - type