{
    "CreationTimeUnixTimeInMs": 1518615120141, 
    "Creator": "admin", 
    "Description": "Get information about IP addresses and enrich them", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"EntityResult\": {\"macAddress\": \"\", \"severityLow\": \"0\", \"links\": [], \"ip\": \"1.1.1.1\", \"lastScan\": \"1549425224\", \"severityCritical\": \"0\", \"total\": \"2\", \"severityAll\": \"0,0,0,0,2\", \"mcafeeGUID\": \"\", \"policyName\": \"1e2e4247-0de7-56d5-8026-34ab1f3150ef-1130313/Basic Discovery Scan\", \"uuid\": \"\", \"lastAuthRun\": \"\", \"severityInfo\": \"2\", \"osCPE\": \"\", \"uniqueness\": \"repositoryID,ip,dnsName\", \"dnsName\": \"google-public-dns-a.google.com\", \"repository\": {\"id\": \"1\", \"description\": \"\", \"name\": \"repo\"}, \"lastUnauthRun\": \"1549363419\", \"biosGUID\": \"\", \"tpmID\": \"\", \"score\": \"0\", \"hasPassive\": \"No\", \"pluginSet\": \"201902020242\", \"hasCompliance\": \"No\", \"severityHigh\": \"0\", \"netbiosName\": \"\", \"severityMedium\": \"0\", \"os\": \"\"}, \"Entity\": \"1.1.1.1\"}]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "TenableSecurityCenter", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1518615120141, 
    "Name": "Enrich IP", 
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1519286884436, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "The repository name.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1519286884436, 
            "Name": "Repository Name", 
            "Type": 0, 
            "Value": ""
        }
    ], 
    "ScriptResultName": "is_success", 
    "SimulationDataJson": "{\"Entities\": [\"ADDRESS\"]}", 
    "Type": 0, 
    "Version": 0.0
}