{
    "CreationTimeUnixTimeInMs": 1515630555632,
    "Creator": "admin",
    "Description": "Run script on a remote machine",
    "Id": -1,
    "IntegrationIdentifier": "SSH",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1515630555632,
    "Name": "Execute Program",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1516072646103,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Remote server address(e.g: x.x.x.x).",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1516072646103,
            "Name": "Remote Server",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1516072646103,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1516072646103,
            "Name": "Remote Username",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1516072646103,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1516072646103,
            "Name": "Remote Password",
            "Type": 12,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1516072646103,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1516072646103,
            "Name": "Remote Port",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1516072646103,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "The path to the program in the remote host.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1516072646103,
            "Name": "Remote Program Path",
            "Type": 0,
            "Value": ""
        }
    ],
    "ScriptResultName": "results",
    "Type": 0,
    "Version": 0.0,
    "SimulationDataJson": "{\"Entities\": []}"
}