{
    "CreationTimeUnixTimeInMs": 1518545061791,
    "Creator": "admin",
    "Description": "The action will add the specified label name to the specified threat IDs",
    "Id": -1,
    "IntegrationIdentifier": "BlueLiv",
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1518545061791,
    "Name": "Add Labels to Threats",
    "Parameters": [        
        {
            "CreationTimeUnixTimeInMs": 1528797117828, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Specify the module type the resource belongs to", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1528797117828, 
            "Name": "Module Type", 
            "Type": 0, 
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1528797117828, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Specify the module ID the resource belongs to", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1528797117828, 
            "Name": "Module ID", 
            "Type": 0, 
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1528797117828, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Specify the Resource IDs, as a comma separated list, to add the labels to", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1528797117828, 
            "Name": "Resource ID", 
            "Type": 0, 
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1528797117828, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Specify the label names you would like to apply to the specified threats, as a comma separated list. Please pay attention to lowercase and uppercase.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1528797117828, 
            "Name": "Label Names", 
            "Type": 0, 
            "Value": ""
        }
    ],
    "ScriptResultName": "is_success",
    "Type": 0,
    "Version": 1.0,
    "SimulationDataJson": "{\"Entities\": []}"
}