{
    "CreationTimeUnixTimeInMs": 1518545061791,
    "Creator": "admin",
    "Description": "The action will remove the specified labels from the specified threat IDs.",
    "Id": -1,
    "IntegrationIdentifier": "BlueLiv",
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1518545061791,
    "Name": "Remove Labels From Threats",
    "Parameters": [        
        {
            "CreationTimeUnixTimeInMs": 1528797117828, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Specify the module type the resource belongs to.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1528797117828, 
            "Name": "Module Type", 
            "Type": 0, 
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1528797117828, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Specify the module ID the resource belongs to.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1528797117828, 
            "Name": "Module ID", 
            "Type": 0, 
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1528797117828, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Specify a comma-separated list of  resource IDs from which you want to remove labels.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1528797117828, 
            "Name": "Resource ID", 
            "Type": 0, 
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1528797117828, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Specify a comma-separated list of labels that need to be removed. Please pay attention to lowercase and uppercase.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1528797117828, 
            "Name": "Label Names", 
            "Type": 0, 
            "Value": ""
        }
    ],
    "ScriptResultName": "is_success",
    "Type": 0,
    "Version": 1.0,
    "SimulationDataJson": "{\"Entities\": []}"
}