{
    "CreationTimeUnixTimeInMs": 1514452450374,
    "Creator": "admin",
    "Description": "Add new entry to active list in ArcSight. Column values are separated by delimiter ‘|' and entries are separated by ‘;’ in parameter ‘Entries’. Column names are separated by delimiter ‘;’ in parameter ‘Columns’. You can also use Entries JSON instead of ‘Columns’ + 'Entries’“.",
    "Id": -1,
    "IntegrationIdentifier": "Arcsight",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1514452450374,
    "Name": "Add Entries To Activelist",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1516724358409,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify the name of the columns, where you want to put values for the entries. Format: Column_name1;Column_name2",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1516724358409,
            "Name": "Columns",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1516724358409,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify the entries. Format entry1_value1|entry1_value2;entry2_value1|entry2_value2",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1516724358409,
            "Name": "Entries",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1516724358409,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify the UUID of the active list, where you want to add new entries. Note: parameter “Active list UUID“ takes priority over “Active list name“. Example: HLZRc9yYBABC-lHtlf3-f0Q==",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1516724358409,
            "Name": "Active List UUID",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1516724358409,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify the name of the active list, where you want to add new entries. Note: parameter “Active list UUID“ takes priority over “Active list name“.",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1516724358409,
            "Name": "Active list name",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1516724358409,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify a list of JSON objects that contain information about the entry. Note: Combination of ‘Columns' and ‘Entries’ parameters have priority over 'Entries JSON’. Format: [{\"Column_1\": \"Value_1\", \"Column_2\": \"Value_2\"}, {\"Column_1\": \"Value_3\", \"Column_2\": \"Value_4\"}]",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1516724358409,
            "Name": "Entries JSON",
            "Type": 0,
            "Value": ""
        }
    ],
    "ScriptResultName": "is_succeed",
    "Type": 0,
    "Version": 2.0,
    "SimulationDataJson": "{\"Entities\": []}"
}