{
    "CreationTimeUnixTimeInMs": 1510669758389,
    "Creator": "admin",
    "Description": "Action checks, if entities were found in ArcSight Activelist",
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"Name\":\"hash\",\"ResourceType\":\"ad\",\"Path\":\"dsa\",\"StartTime\":\"asd\",\"EventClassID\":\"dsa\",\"Status\":\"sasd\",\"Duration\":\"sad\"}]",
            "ResultName": "JsonResult"
        }
    ],
    "Id": -1,
    "IntegrationIdentifier": "Arcsight",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1510669758389,
    "Name": "Is Value In Activelist Column",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1516872800390,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify the UUID of the active list, where you want to search for entities. Note: parameter “Active list UUID“ takes priority over “Active list name“. Example: HLZRc9yYBABC-lHtlf3-f0Q==",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1516872800390,
            "Name": "Active list UUID",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1516872800390,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify the name of the column, where you want to search for the entity.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1516872800390,
            "Name": "Column name",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1516872800390,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify the name of the active list, where you want to search for entities. Note: parameter “Active list UUID“ takes priority over “Active list name“.",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1516872800390,
            "Name": "Active list name",
            "Type": 0,
            "Value": ""
        }
    ],
    "ScriptResultName": "Success_Indicator",
    "Type": 0,
    "Version": 2.0,
    "SimulationDataJson": "{\"Entities\": []}"
}