{
    "CreationTimeUnixTimeInMs": 1668078112000,
    "Creator": "admin",
    "Description": "Test connectivity to the Automox with parameters provided at the integration configuration page on the Marketplace tab",
    "Id": -1,
    "IntegrationIdentifier": "Automox",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1668078112000,
    "Name": "Ping",
    "Parameters": [],
    "ScriptResultName": "is_success",
    "Version": 0.0,
    "SimulationDataJson": "{\"Entities\": []}"
}