INTEGRATION_NAME = "ProofPointTAP"
INTEGRATION_DISPLAY_NAME = "ProofPoint TAP"

PING_SCRIPT_NAME = f"{INTEGRATION_NAME} - Ping"
GET_CAMPAIGN_SCRIPT_NAME = f"{INTEGRATION_NAME} - Get Campaign"
DECODE_URL_SCRIPT_NAME = f"{INTEGRATION_NAME} - Decode URL"


LIMIT_DEFAULT = 50
MAX_LIMIT = 1000

CAMPAIGNS_TABLE_NAME = "Campaign Details"
CAMPAIGN_EVIDENCE_TABLE_NAME = "Campaign {id} Evidence"
