PRIORITIES = [u'LOW', u'MEDIUM', u'HIGH']
DEVICE_VENDOR = u'Symantec'
DEVICE_PRODUCT = u'Symantec ATP'
WHITELIST_FILTER = u'whitelist'
BLACKLIST_FILTER = u'blacklist'
INCIDENTS_CONNECTOR_NAME = u'Symantec ATP Incidents Connector'
SYMANTEC_TO_SIEM_PRIORITY = {
    1: 40,
    2: 60,
    3: 80
}
SIEM_TO_SYMANTEC_PRIORITY = {
    u'LOW': 1,
    u'MEDIUM': 2,
    u'HIGH': 3
}
ATP_QUERIES_TIME_FORMAT = u'%Y-%m-%dT%H:%M:%S.%fZ'
MIN_INCIDENTS_TO_FETCH = 100
MAX_INCIDENTS_TO_FETCH = 1000
LATEST_EVENTS_FOR_INCIDENT = 100
LIMIT_IDS_IN_IDS_FILE = 3000
IDS_HOURS_LIMIT = 72
ALERT_ID_FIELD = u'uuid'
ACCEPTABLE_TIME_INTERVAL_IN_MINUTES = 5
