{
    "CreationTimeUnixTimeInMs": 1520849620948, 
    "Creator": "admin", 
    "Description": "Download a binary", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"EntityResult\": \"TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIb\", \"Entity\": \"82A2C91219F140BB2A4FE34A7390B6C7\"}]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "CBResponse", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1520849620948, 
    "Name": "Download Binary", 
    "Parameters": [], 
    "ScriptResultName": "is_success", 
    "SimulationDataJson": "{\"Entities\": [\"FILEHASH\"]}", 
    "Type": 0, 
    "Version": 0.0
}