{
    "CreationTimeUnixTimeInMs": 1521035120216,
    "Creator": "admin",
    "Description": "Get information about a VM",
    "DynamicResultsMetadata": [
        {
            "ResultExample": "{\"Guest\": \"Microsoft Windows 7 (64-bit)\", \"Bios UUID\": \"423503ea-af3c-58a8-188c-f6285cec98e5\", \"VMware Tools\": \"toolsNotInstalled\", \"Ip Address\": \"1.1.1.1\", \"State\": \"poweredOn\", \"Template\": false, \"Path\": \"[DataStore] vm/vn.vmx\", \"Name\": \"vm\", \"Instance UUID\": \"50359be7-424b-e53d-5133-3f98f0e705ef\"}",
            "ResultName": "JsonResult"
        }
    ],
    "Id": -1,
    "IntegrationIdentifier": "VSphere",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1521035120216,
    "Name": "Get System Info",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1521035171304,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Target VM name.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1521035171304,
            "Name": "Vm Name",
            "Type": 0,
            "Value": ""
        }
    ],
    "ScriptResultName": "success",
    "Type": 0,
    "Version": 0.0,
    "SimulationDataJson": "{\"Entities\": []}"
}