{
    "CreationTimeUnixTimeInMs": 1521035189969,
    "Creator": "admin",
    "Description": "Get a list of all registered VMs",
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"Guest\": \"Microsoft Windows 7 (64-bit)\", \"Bios UUID\": \"423503ea-af3c-58a8-188c-f6285cec98e5\", \"VMware Tools\": \"toolsNotInstalled\", \"Ip Address\": \"1.1.1.1\", \"State\": \"poweredOn\", \"Template\": false, \"Path\": \"[DataStore] vm/vn.vmx\", \"Name\": \"vm\", \"Instance UUID\": \"50359be7-424b-e53d-5133-3f98f0e705ef\"}]",
            "ResultName": "JsonResult"
        }
    ],
    "Id": -1,
    "IntegrationIdentifier": "VSphere",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1521035189969,
    "Name": "List Vms",
    "Parameters": [],
    "ScriptResultName": "vm_names",
    "Type": 0,
    "Version": 0.0,
    "SimulationDataJson": "{\"Entities\": []}"
}