{
    "CreationTimeUnixTimeInMs": 1518516430366, 
    "Creator": "admin", 
    "Description": "Add URLs to a given URL category (NOTE- To actually block the URL, create a policy and add the desired URL category to it.). Note: the length of URL can't exceed 255 characters.", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "{\"success\":[\"www.abc.com\"],\"failure\":[\"www.abc.com\"],\"already_exist\":[\"www.abc.com\"]}",
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "PaloAltoNGFW", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1518516430366, 
    "Name": "Block Urls", 
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1518700571020, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "The device name in which the group is located. The default device name of NGFW is localhost.localdomain. In case configured differently, please refer to https://<NGFWIP>/php/rest/browse.php/config::devices for the list of all the device names and select the relevant device.", 
            "Id": -1, 
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1518700571020, 
            "Name": "Device Name", 
            "Type": 0, 
            "Value": ""
        }, 
        {
            "CreationTimeUnixTimeInMs": 1518700571020, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "The vsys in which the group is located. The default vsys name of NGFW is vsys1. In case configured differently, please refer to https://<NGFW IP>/php/rest/browse.php/config::devices::entry[@name='<DEVICE NAME>']::vsys for the list of all the vsys names of the device and select the relevant vsys.", 
            "Id": -1, 
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1518700571020, 
            "Name": "Vsys Name", 
            "Type": 0, 
            "Value": ""
        }, 
        {
            "CreationTimeUnixTimeInMs": 1518700571020, 
            "CustomActionId": -1, 
            "DefaultValue": "", 
            "Description": "Policy name value.", 
            "Id": -1, 
            "IsMandatory": true, 
            "ModificationTimeUnixTimeInMs": 1518700571020, 
            "Name": "URL Category Name", 
            "Type": 0, 
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1520155470744,
            "CustomActionId": -1,
            "DefaultValue": false,
            "Description": "If enabled, action will use shared objects instead of vsys.",
            "Id": -1,
            "IsMandatory": false,
            "ModificationTimeUnixTimeInMs": 1520155470744,
            "Name": "Use Shared Objects",
            "Type": 1,
            "Value": false
        }
    ], 
    "ScriptResultName": "success", 
    "SimulationDataJson": "{\"Entities\": [\"DestinationURL\"]}", 
    "Type": 0, 
    "Version": 0.0
}