{
    "CreationTimeUnixTimeInMs": 1517826278026,
    "Creator": "admin",
    "Description": "List all blocked applications in a given policy",
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[\"1und1-mail\", \"Filter\", \"Group1\", \"SiemplifyAppBlacklist\", \"apple-siri\", \"google-analytics\"]",
            "ResultName": "JsonResult"
        }
    ],
    "Id": -1,
    "IntegrationIdentifier": "PaloAltoNGFW",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1517826278026,
    "Name": "Get Blocked Applications",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1518700589889,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "The device name in which the group is located. The default device name of NGFW is localhost.localdomain. In case configured differently, please refer to https://<NGFWIP>/php/rest/browse.php/config::devices for the list of all the device names and select the relevant device.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1518700589889,
            "Name": "Device Name",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1518700589889,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "The vsys in which the group is located. The default vsys name of NGFW is vsys1. In case configured differently, please refer to https://<NGFW IP>/php/rest/browse.php/config::devices::entry[@name='<DEVICE NAME>']::vsys for the list of all the vsys names of the device and select the relevant vsys.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1518700589889,
            "Name": "Vsys Name",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1518700589889,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Policy name value.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1518700589889,
            "Name": "Policy Name",
            "Type": 0,
            "Value": ""
        }
    ],
    "ScriptResultName": "blocked_applications",
    "Type": 0,
    "Version": 0.0,
    "SimulationDataJson": "{\"Entities\": []}"
}