{
    "CreationTimeUnixTimeInMs": 1518092219730, 
    "Creator": "admin", 
    "Description": "Get a summary classification report and all details for a sample or a list of samples using hash value(s)", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"EntityResult\": {\"threat_status\": \"malicious\", \"local_last_seen\": \"2019-01-22T14: 21: 35.513535Z\", \"classification_origin\": {\"imphash\": \"\", \"sha1\": \"9747d177bddfc9809079283829e6bbbe315dc000\", \"sha512\": \"efabb440ab2b82dda2614308b8e2d5e1850ede3fb9c8e6f1e521f1b0728d621a6f5174c30b8e27d7964bcff0ae6b8a1a48ecc4a69d0dc3eae7eccf54a4791000\", \"sha256\": \"d3133784ef82208faaa3b917096d7c3e0ad9eb89a5eb4d7770418c8261da4000\", \"md5\": \"242b13c72845a90a869ed0add78f6000\"}, \"threat_name\": \"Android.Trojan.Agent\", \"local_first_seen\": \"2018-01-21T15: 30: 36.698843Z\", \"classification_reason\": \"cloud\", \"threat_level\": 5, \"trust_factor\": 5, \"md5\": \"2f61c5a77a64b3d45d651dc2fa7ba000\", \"aliases\": [\"76ea783ed0744703347a00403a73694c2a1e5a957f0f969b4284353fc7c91000\"]}, \"Entity\": \"2f61c5a77a64b3d45d651dc2fa7ba000\"}]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "ReversinglabsA1000", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1518092219730, 
    "Name": "Get Report", 
    "Parameters": [], 
    "ScriptResultName": "is_success", 
    "SimulationDataJson": "{\"Entities\": [\"FILEHASH\"]}", 
    "Type": 0, 
    "Version": 0.0
}