ALERTS_CONNECTOR_NAME = u'FireEye EX - Alerts Connector'
TIMEOUT_THRESHOLD = 0.9
HOURS_LIMIT_IN_IDS_FILE = 72
TEST_OFFSET_HOURS = 24
DURATION = u'48_hours'
MAP_FILE = u'map.json'
IDS_FILE = u'ids.json'
DEVICE_VENDOR = u'FireEye'
DEVICE_PRODUCT = u'FireEye EX'
ALERT_NAME = u'Malicious Email'
PRINT_TIME_FORMAT = u'%Y-%m-%d %H:%M:%S.%f'
