{
    "CreationTimeUnixTimeInMs": 1520757117753, 
    "Creator": "admin", 
    "Description": "Delete file remediation action", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"EntityResult\": 13590, \"Entity\": \"0DC213FE4551740E12CAC575A9880753A9DACD510533F31BD7F635E743A7605\"}]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "Cynet", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1520757117753, 
    "Name": "Delete Hash In Hosts", 
    "Parameters": [], 
    "ScriptResultName": "is_success", 
    "SimulationDataJson": "{\"Entities\": [\"FILEHASH\"]}", 
    "Type": 0, 
    "Version": 0.0
}