{
    "CreationTimeUnixTimeInMs": 1516712226206, 
    "Creator": "admin", 
    "Description": "Query DShield for information about external IP addresses", 
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"EntityResult\": {\"comment\": \"Googlepublicrecursivenameserver\", \"count\": 8218, \"updated\": \"2019-01-2004: 51: 46\", \"alexa\": {\"domains\": 1, \"lastrank\": 6178, \"hostname\": \"google-public-dns-a.google.com\", \"lastseen\": \"2016-01-02\", \"firstseen\": \"2016-01-02\"}, \"network\": \"1.1.1.1/24\", \"attacks\": 32, \"maxdate\": \"2019-01-20\", \"asname\": \"GOOGLE-GoogleLLC\", \"assize\": 609498, \"number\": \"1.1.1.1\", \"maxrisk\": 0, \"as\": 15169, \"asabusecontact\": \"john_doe@example.com\", \"ascountry\": \"US\", \"threatfeeds\": {\"qakbot\": {\"lastseen\": \"2015-04-03\", \"firstseen\": \"2015-04-02\"}, \"forumspam\": {\"lastseen\": \"2018-12-05\", \"firstseen\": \"2011-05-10\"}}, \"mindate\": \"2019-01-14\"}, \"Entity\": \"1.1.1.1\"}]", 
            "ResultName": "JsonResult"
        }
    ], 
    "Id": -1, 
    "IntegrationIdentifier": "DShield", 
    "IsCustom": false, 
    "IsEnabled": true, 
    "ModificationTimeUnixTimeInMs": 1516712226206, 
    "Name": "Get Ip Info", 
    "Parameters": [], 
    "ScriptResultName": "is_enriched", 
    "SimulationDataJson": "{\"Entities\": [\"ADDRESS\"]}", 
    "Type": 0, 
    "Version": 0.0
}