{
    "CreationTimeUnixTimeInMs": 1517416644721,
    "Creator": "admin",
    "Description": "Add attachment to a table record in ServiceNow.",
    "Id": -1,
    "DynamicResultsMetadata": [
        {
            "ResultExample": "[{\"result\": {\"sys_tags\": \"\", \"sys_updated_by\": \"admin\", \"hash\": \"c9d04c9565fc665c80681fb1d829938026871f66e14f501e08531df66938axxx\", \"content_type\": \"multipart/form-data\", \"chunk_size_bytes\": \"700000\", \"file_name\": \"Example.txt\", \"sys_updated_on\": \"2020-09-02 05:55:32\", \"sys_created_on\": \"2020-09-02 05:55:32\", \"image_width\": \"\", \"image_height\": \"\", \"state\": \"pending\", \"sys_mod_count\": \"0\", \"table_name\": \"sys_product_help\", \"sys_id\": \"30b0ea302f031010c518532a2799bxxx\", \"download_link\": \"https://devXXXX.service-now.com/api/now/attachment/30b0ea302f031010c518532a2799bxxx/file\", \"average_image_color\": \"\", \"size_bytes\": \"5\", \"table_sys_id\": \"003a3ef24ff1120031577d2ca310cxxx\", \"size_compressed\": \"25\", \"sys_created_by\": \"admin\", \"compressed\": \"true\"}}]",
            "ResultName": "JsonResult"
        }
    ],
    "IntegrationIdentifier": "ServiceNow",
    "IsCustom": false,
    "IsEnabled": true,
    "ModificationTimeUnixTimeInMs": 1517416644721,
    "Name": "Add Attachment",
    "Parameters": [
        {
            "CreationTimeUnixTimeInMs": 1517836054743,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify name of the table, where is located the record to which you want to add attachment.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1517836054743,
            "Name": "Table Name",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1517836054743,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify sys id of the record to which you want to add attachment.  ",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1517836054743,
            "Name": "Record Sys ID",
            "Type": 0,
            "Value": ""
        },
        {
            "CreationTimeUnixTimeInMs": 1517836054743,
            "CustomActionId": -1,
            "DefaultValue": "",
            "Description": "Specify a comma-separated list of absolute paths to the files that need to be attached.",
            "Id": -1,
            "IsMandatory": true,
            "ModificationTimeUnixTimeInMs": 1517836054743,
            "Name": "File Path",
            "Type": 0,
            "Value": ""
        }
    ],
    "ScriptResultName": "is_success",
    "Type": 0,
    "Version": 1.0,
    "SimulationDataJson": "{\"Entities\": []}"
}